activities/urls.py
from django.urls import path
from . import views

app_name = 'activities'

urlpatterns = [
    path('land_info_list/', views.LandInfoListView.as_view(), name='land_info_list'),
    path('user_land_info_list/', views.UserLandInfoListView.as_view(), name='user_land_info_list'),
    path('create/', views.LandInfoCreateView.as_view(), name='land_info_create'),
    path('<int:pk>/update/', views.LandInfoUpdateView.as_view(), name='land_info_update'),
    path('<int:pk>/', views.LandInfoDetailView.as_view(), name='land_info_detail'),
    path('detail/<int:pk>/', views.UserLandInfoDetailView.as_view(), name='user_land_info_detail'),
    path('<int:pk>/delete/', views.LandInfoDeleteView.as_view(), name='land_info_delete'),
]

app_users/urls.py
from django.urls import path
from .  import views

urlpatterns=[
    path('',views.HomeView.as_view(),name="index"),
    path('dashboard/',views.DashboardView.as_view(),name="dashboard"),
    path('user_about/',views.AboutView.as_view(),name="about"),
    path('user_login/',views.user_login.as_view(),name="user_login"),
    path('user_logout/',views.user_logout,name="user_logout"),
    path('register/',views.register,name="register"),
    path('contact/',views.ContactView.as_view(),name="contact"),
]

landinfosys/urls.py
from django.contrib import admin
from django.urls import path
import app_users
import activities
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_users.urls')),
    path('',include('activities.urls',namespace='activities')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

activities/models.py
from django.db import models
import os
from django.contrib.auth.models import User


def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.id:
        filename = 'LandInfo_Pictures/{}.{}'.format(instance.owner, ext)
    return os.path.join(upload_to, filename)


def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.id:
        filename = 'certificate_files/{}/{}.{}'.format(instance.owner, instance.owner, ext)
        if os.path.exists(filename):
            new_name = str(instance.id) + str('1')
            filename = 'lesson_images/{}/{}.{}'.format(instance.owner, new_name, ext)
    return os.path.join(upload_to, filename)


# Create your models here.
class LandInfo(models.Model):
    RENTAL = "RENTAL"
    AVAILABLE = "AVAILABLE"
    SOLD = "SOLD"

    STATUS = (
        (RENTAL, 'Rental'),
        (AVAILABLE, 'Available'),
        (SOLD, 'Sold'),
    )

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='land_user')
    land_status = models.CharField(max_length=30, choices=STATUS, default=AVAILABLE)
    email = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=400, null=True, blank=True)
    land_size = models.CharField(max_length=150)
    price = models.FloatField(max_length=20)
    plot = models.FloatField(max_length=20)
    location = models.CharField(max_length=200)
    image = models.ImageField(upload_to=save_subject_image, verbose_name='Land Picture')
    lga_situated = models.CharField(max_length=400, null=True, blank=True)
    state = models.CharField(max_length=400, null=True, blank=True)
    certificate = models.ImageField(upload_to=save_subject_image, verbose_name="Land certificate", null=True, blank=True)

    def __str__(self):
        return self.email

activities/forms.py
from django import forms
from .models import LandInfo
from django.utils.translation import gettext_lazy as _


class LandRegister(forms.ModelForm):
    RENTAL="RENTAL"
    AVAILABLE="AVAILABLE"
    SOLD="SOLD"

    STATUS=(
        (RENTAL,'Rental'),
        (AVAILABLE,'Available'),
        (SOLD,'Sold'),
    )
    land_status = forms.ChoiceField(required=True, choices=STATUS)
    class Meta():
        model = LandInfo
        fields = ('email','plot','land_size','description','price','location','image','lga_situated','state','land_status','certificate')
        labels={'email':_('Email'),'plot':_('Plot'),'land_size':_('Land size'),
                'description':_('Land description'),'price':_('Price'),
                'location':_('Location'),'image':_('Land image'),'lga_situated':_('LGA situated'),
                'state':_('State'),'land_status':_('Land status'),'certificate':_('Certificate of occupancy')}

activities/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,DetailView,UpdateView,DeleteView
from .forms import LandRegister
from .models import LandInfo
# Create your views here.

class LandInfoListView(ListView):
    context_object_name = 'lands'
    model=LandInfo
    template_name = 'activities/land_info_list.html'


class UserLandInfoListView(ListView):
    context_object_name = 'lands'
    model=LandInfo
    template_name = 'activities/user_land_info_list.html'

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        queryset = LandInfo.objects.filter(owner=user)
        return queryset

class LandInfoDetailView(DetailView):
    model=LandInfo
    context_object_name = 'land'
    template_name = 'activities/land_info_detail.html'

class UserLandInfoDetailView(DetailView):
    model=LandInfo
    context_object_name = 'land'
    template_name = 'activities/user_land_info_detail.html'

class LandInfoCreateView(CreateView):
    form_class = LandRegister
    model=LandInfo
    context_object_name = 'land'
    template_name = 'activities/land_info_create.html'


    def get_success_url(self):
        return reverse_lazy('activities:land_info_list')


    def form_valid(self, form, *args, **kwargs):
        fm = form.save(commit=False)
        fm.owner = self.request.user
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LandInfoUpdateView(UpdateView):
    form_class = LandRegister
    template_name = 'activities/land_info_update.html'
    context_object_name = 'land'
    model=LandInfo

    def get_success_url(self):
        return reverse_lazy('activities:land_info_list')

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.owner = self.request.user
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LandInfoDeleteView(DeleteView):
    model= LandInfo
    context_object_name = 'land'
    template_name = 'activities/land_info_delete.html'

    def get_success_url(self):
        return reverse_lazy('activities:land_info_list')


activities/templates/activities/land_info_create.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Land registration {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" >Land registration </h2>
        <!-- divider -->
        <hr style="color:#ff5722;">
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Register a land</h2>
              <!-- class row for description-->        
</section>

<div class="container d-flex align-items-center justify-content-center">
  <div class="row d-flex justify-content-center">
<form method="post" enctype="multipart/form-data">
  <div class="form-group">
  {% csrf_token %}
  {{form|crispy}}
  <div class="row my-3">
  <input class="btn btn-success btn-lg btn-block" type="submit" value="Create">
  </div>
  </div>
</form>
  </div>
</div>
{% endblock %}

activities/templates/activities/land_info_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Delete a registered land {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Land deletion </h2>
        <div class="row d-flex justify-content-center text-center">

        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
  </div>
</header>
{% endblock %}



{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#f8e0d8;">Delete a land at {{land.location}} with the price of {{land.price}}</h2>
              <!-- class row for description-->
</section>

<h3 class="mb-4" style="color:#ff5722;">Are you sure you want to delete this land?</h3>

<form method="post">
  {% csrf_token %}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Delete" class="btn btn-danger btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'activities:land_info_detail' pk=land.pk %}" class="btn btn-warning btn-block">Cancel Deletion</a>
        </div>
  </div>
</form>

{% endblock %}

activities/templates/activities/land_info_detail.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %} Everything you need to know about this land {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col text-white">
        <!-- heading -->
        <h2 class="display-6 font-weight-bold  p-5 " style="color:#ff5722;" >land at {{land.location}}</h2>
        <div class="row d-flex justify-content-center text-center">
        </div>
        <!-- divider -->
        <hr style="color:#ff5722;">
  </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center">
    <h2 class="mb-0 mt-5 font-weight-bold" style="color:#ff5722;">Land Details</h2>
    <div class="row d-flex justify-content-center mb-3">
      <blockquote class="blockquote mt-0">
        <footer class="blockquote-footer">Created on {{land.created_at}} by <cite title="Source Title">{{land.owner}}</cite></footer>
        </blockquote>
    </div>
    <!-- video -->
    <div class="row d-flex justify-content-center mb-3">
        <div class="row d-flex justify-content-center mb-3">
            <div class="col-md-3">
                <div class="card box-shadow-hover">
                <div class="card-header">
                    <img src="{{land.image.url|default_if_none:'#'}}" class="card-img" alt="No image found" height="200px" width="200px">
                </div>
                <div class="card-body">
                    <h5 class="card-title py-2">Land Owner : {{land.owner}} <hr style="color:#ff5722;height:4px;" /></h5>
                    <p class="card-text">Land Description :{{land.description}}</p>
                </div>
            </div>
            </div>
            <div class="col-md-9">
                <div class="table-responsive-sm table-responsive-md table-responsive-xl table-responsive-lg table-responsive-xxl table-bordered border-primary">
                    <table class="table">
                        <tr>
                            {% if land.email %}
                            <th scope="row">Email:</th>
                            <td>{{land.email}}</td>
                            {% endif %}
                            {% if land.created_at %}
                            <th scope="row">Created on the:</th>
                            <td>{{land.created_at}}</td>
                            {% endif %}
                            {% if land.land_size %}
                            <th scope="row">Land size :</th>
                            <td>{{land.land_size}}</td>
                            {% endif %}
                            <br />
                        </tr>
                          <tr>
                            {% if land.price %}
                            <th scope="row">Price:</th>
                            <td>{{land.price}}</td>
                            {% endif %}
                            {% if land.plot %}
                            <th scope="row">Plot:</th>
                            <td>{{land.plot}}</td>
                            {% endif %}
                            {% if land.location %}
                            <th scope="row">Location:</th>
                            <td>{{land.location}}</td>
                            {% endif %}
                            <br />
                          </tr>
                          <tr>
                            {% if land.lga_situated %}
                            <th scope="row">LGA situated:</th>
                            <td>{{land.situated}}</td>
                            {% endif %}
                            {% if land.state %}
                            <th scope="row">State:</th>
                            <td>{{land.state}}</td>
                            {% endif %}
                            {% if land.certificate %}
                            <th scope="row">Certificate:</th>
                            <td>{{land.certiificate}}</td>
                            {% endif %}

                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

{%endblock%}

activities/templates/activities/land_info_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Display list of land {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col text-white">
        <!-- heading -->
        <h2 class="display-6 font-weight-bold  p-5 " style="color:#ff5722;" >LandIS Details </h2>
        <div class="row d-flex justify-content-center text-center">
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">
  </div>
</header>
{% endblock %}


{% block content %}
<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Dive Deeper</h2>
              <!-- class row for description-->
              <!-- class row2 for cards -->
              <div class="row d-flex justify-content-center mb-3">
                {% for land in lands %}
                <div class="col-sm-6 col-md-3">
                  <div class="card box-shadow-hover">
                     <div class="card-header">
                       <img src="{{land.image.url|default_if_none:'#'}}" class="card-img" alt="No image found" height="200px" width="200px">
                     </div>
                    <div class="card-body">
                      <h5 class="card-title py-2">Owned by {{land.owner}} <hr style="color:#ff5722;height:4px;" /></h5>
                       <p class="card-text">{{land.description}}</p>
                      <a href="{% url 'activities:land_info_detail' pk=land.pk %}" >
                        <button class="button-les">View full detail</button>
                      </a>
                    </div>
                  </div>
                </div>
                {% empty %}
                <p>No registered land informations</p>
                {% endfor %}
              </div>

</section>
{%endblock%}

activities/templates/activities/land_info_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Update land information {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" >Update land information </h2>
        <div class="row d-flex justify-content-center text-center">
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">
       </div>
  </div>
  </div>
</header>
{% endblock %}


{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Update</h2>
              <!-- class row for description -->
</section>


<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form|crispy}}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Update" class="btn btn-warning btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'activities:land_info_detail' pk=land.pk %}" class="btn btn-danger btn-block">Cancel Update</a>
        </div>
</div>
</form>

{% endblock %}

activities/templates/activities/user_land_info_detail.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %} Everything you need to know about this land {% endblock %}

{% block image_block %}
<header class="info-header">
    <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
        <div class="row d-flex justify-content-center text-center">
            <div class="col text-white">
                <!-- heading -->
                <h2 class="display-6 font-weight-bold  p-5 " style="color:#ff5722;" >land at {{land.location}}</h2>
                <div class="row d-flex justify-content-center text-center">
                </div>
                <!-- divider -->
                <hr style="color:#ff5722;">
            </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center">
    <h2 class="mb-0 mt-5 font-weight-bold" style="color:#ff5722;">Land Details</h2>
    <div class="row d-flex justify-content-center mb-3">
        <blockquote class="blockquote mt-0">
            <footer class="blockquote-footer">Created on {{land.created_at}} by <cite title="Source Title">{{land.owner}}</cite></footer>
        </blockquote>
    </div>
    <!-- video -->
    <div class="row d-flex justify-content-center mb-3">
        <div class="row d-flex justify-content-center mb-3">
            <div class="col-md-3">
                <div class="card box-shadow-hover">
                    <div class="card-header">
                        <img src="{{land.image.url|default_if_none:'#'}}" class="card-img" alt="No image found" height="200px" width="200px">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title py-2">Land Owner : {{land.owner}} <hr style="color:#ff5722;height:4px;" /></h5>
                        <p class="card-text">Land Description :{{land.description}}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="table-responsive-sm table-responsive-md table-responsive-xl table-responsive-lg table-responsive-xxl table-bordered border-primary">
                    <table class="table">
                        <tr>
                            {% if land.email %}
                            <th scope="row">Email:</th>
                            <td>{{land.email}}</td>
                            {% endif %}
                            {% if land.created_at %}
                            <th scope="row">Created on the:</th>
                            <td>{{land.created_at}}</td>
                            {% endif %}
                            {% if land.land_size %}
                            <th scope="row">Land size :</th>
                            <td>{{land.land_size}}</td>
                            {% endif %}
                            <br />
                        </tr>
                        <tr>
                            {% if land.price %}
                            <th scope="row">Price:</th>
                            <td>{{land.price}}</td>
                            {% endif %}
                            {% if land.plot %}
                            <th scope="row">Plot:</th>
                            <td>{{land.plot}}</td>
                            {% endif %}
                            {% if land.location %}
                            <th scope="row">Location:</th>
                            <td>{{land.location}}</td>
                            {% endif %}
                            <br />
                        </tr>
                        <tr>
                            {% if land.lga_situated %}
                            <th scope="row">LGA situated:</th>
                            <td>{{land.situated}}</td>
                            {% endif %}
                            {% if land.state %}
                            <th scope="row">State:</th>
                            <td>{{land.state}}</td>
                            {% endif %}
                            {% if land.certificate %}
                            <th scope="row">Certificate:</th>
                            <td>{{land.certiificate}}</td>
                            {% endif %}

                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>


    <!-- update and delete button -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
        {% if user.is_authenticated or user.is_superuser %}
        <div class="col-md-6 mb-3 text-center">
            <a href="{% url 'activities:land_info_update' pk=land.pk %}" class="btn btn-warning btn-lg mr-4 btn-block">Update LandInfo</a>
        </div>
        <div class="col-md-6">
            <a href="{% url 'activities:land_info_delete'  pk=land.pk %}" class="btn btn-danger btn-lg mr-4 btn-block"> Delete LandInfo </a>
        </div>
        {% endif %}
    </div>
</section>


{%endblock%}

activities/templates/activities/user_land_info_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Display list of land {% endblock %}

{% block image_block %}
<header class="info-header">
    <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
        <div class="row d-flex justify-content-center text-center">
            <div class="col text-white">
                <!-- heading -->
                <h2 class="display-6 font-weight-bold  p-5 " style="color:#ff5722;" >LandIS Details </h2>
                <div class="row d-flex justify-content-center text-center">
                </div>

                <!-- divider -->
                <hr style="color:#ff5722;">
            </div>
</header>
{% endblock %}


{% block content %}
<section id="best-features" class="text-center">
    <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Dive Deeper</h2>
    <!-- class row for description-->
    <!-- class row2 for cards -->
    <div class="row d-flex justify-content-center mb-3">
        {% for land in lands %}
        <div class="col-sm-6 col-md-3">
            <div class="card box-shadow-hover">
                <div class="card-header">
                    <img src="{{land.image.url|default_if_none:'#'}}" class="card-img" alt="No image found" height="200px" width="200px">
                </div>
                <div class="card-body">
                    <h5 class="card-title py-2">Owned by {{land.owner}} <hr style="color:#ff5722;height:4px;" /></h5>
                    <p class="card-text">{{land.description}}</p>
                    <a href="{% url 'activities:user_land_info_detail' pk=land.pk %}" >
                        <button class="button-les">View full detail</button>
                    </a>
                </div>
            </div>
        </div>
        {% empty %}
        <p>No registered land informations</p>
        {% endfor %}
    </div>

</section>
{%endblock%}