activities/urls.py
from django.urls import path
from . import views

app_name = 'activities'

urlpatterns = [
    path('land_info_list/', views.LandInfoListView.as_view(), name='land_info_list'),
    path('user_land_info_list/', views.UserLandInfoListView.as_view(), name='user_land_info_list'),
    path('create/', views.LandInfoCreateView.as_view(), name='land_info_create'),
    path('<int:pk>/update/', views.LandInfoUpdateView.as_view(), name='land_info_update'),
    path('<int:pk>/', views.LandInfoDetailView.as_view(), name='land_info_detail'),
    path('detail/<int:pk>/', views.UserLandInfoDetailView.as_view(), name='user_land_info_detail'),
    path('<int:pk>/delete/', views.LandInfoDeleteView.as_view(), name='land_info_delete'),
]

app_users/urls.py
from django.urls import path
from .  import views

urlpatterns=[
    path('',views.HomeView.as_view(),name="index"),
    path('dashboard/',views.DashboardView.as_view(),name="dashboard"),
    path('user_about/',views.AboutView.as_view(),name="about"),
    path('user_login/',views.user_login.as_view(),name="user_login"),
    path('user_logout/',views.user_logout,name="user_logout"),
    path('register/',views.register,name="register"),
    path('contact/',views.ContactView.as_view(),name="contact"),
]

landinfosys/urls.py
from django.contrib import admin
from django.urls import path
import app_users
import activities
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_users.urls')),
    path('',include('activities.urls',namespace='activities')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      {% load static %}
    <meta charset="utf-8">
    <title>{%block title%}{%endblock%}</title>
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    <style>
header{
background:url("{% static 'Images/Australia-013.jpg' %}") no-repeat top center fixed;
background-size: 100% 100%;
width:"100%";
height:"100%";
}
    </style>

  


  </head>
  <body>
    <!-- navigation bar -->
              <nav class="navbar navbar-expand-lg  navbar-light bg-light fixed-top scrolling-navbar">
                <div class="container" >
                    <a class="navbar-brand flex-md-grow-1 mx-4 font-bold " >
                        {% if user.is_authenticated %}
                        LandIS Dashboard
                        {%else %}
                        Land Information Systems
                        {% endif %}
                    </a>
                      <a class="navbar-brand" href="{% url 'index' %}" style="color:#ff5722;" >Home</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basicExampleNav"
                           aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                           <span class="navbar-toggler-icon"></span>
                       </button>
                      <div class="collapse navbar-collapse" id="basicExampleNav" >
                        <ul class=" navbar-nav  mr-auto smooth-scroll " >
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Service
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" href="{% url 'activities:land_info_list' %}">Avaliable Data</a></li>
                                </ul>
                            </li>
                                <!--    
                                  {% if user.is_superuser %}
                                  <li class="nav-item ">
                                     <a class="nav-link" href="{% url 'admin:index' %}">Admin</span> </a>
                                  </li>
                                  {%endif%}
                                -->
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'activities:user_land_info_list' %}">My Enquiry</a>
                            </li>
                            {%endif%}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'about' %}">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'contact'%}">Contact Us</a>
                            </li>
                                {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                 Login as {{user.username}}
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink2">
                                    <li><a class="dropdown-item" href="{% url 'activities:land_info_create' %}">Register a land</a></li>
                                    <li><a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a></li>
                                </ul>
                            </li>

                            {% else %}
                                    <li class="nav-item ">
                                        <a class="nav-link" href="{% url 'user_login' %}">Login</a>
                                    </li>
                                    <li class="nav-item " >
                                       <a class="nav-link" href="{% url 'register' %}">Register</span> </a>
                                    </li>
                                {% endif %}

                           
                        </ul>

                      </div>
                       
                </div>
               
              </nav>
          {% block image_block %}
          {% endblock %}


    <div class="container">
        {%block content%}
        {%endblock%}
    </div>

    <footer class="page-footer mt-5 " style="background-color:blue;">
        <div class="footer-copyright  text-center py-3 text-white">
            <p>© 2021 Copyright: LandIS-Land Information System</p>
        </div>
      </div>
    </footer>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  </body>
</html>